// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Certificate is the predicate function for certificate builders.
type Certificate func(*sql.Selector)

// CoveredPerson is the predicate function for coveredperson builders.
type CoveredPerson func(*sql.Selector)

// Fund is the predicate function for fund builders.
type Fund func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// SchemeType is the predicate function for schemetype builders.
type SchemeType func(*sql.Selector)
