// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/mmildd_s/app/ent/coveredperson"
	"github.com/mmildd_s/app/ent/patient"
	"github.com/mmildd_s/app/ent/predicate"
)

// PatientUpdate is the builder for updating Patient entities.
type PatientUpdate struct {
	config
	hooks      []Hook
	mutation   *PatientMutation
	predicates []predicate.Patient
}

// Where adds a new predicate for the builder.
func (pu *PatientUpdate) Where(ps ...predicate.Patient) *PatientUpdate {
	pu.predicates = append(pu.predicates, ps...)
	return pu
}

// SetPatientName sets the Patient_Name field.
func (pu *PatientUpdate) SetPatientName(s string) *PatientUpdate {
	pu.mutation.SetPatientName(s)
	return pu
}

// SetPatientAge sets the Patient_Age field.
func (pu *PatientUpdate) SetPatientAge(s string) *PatientUpdate {
	pu.mutation.SetPatientAge(s)
	return pu
}

// SetPatientWeight sets the Patient_Weight field.
func (pu *PatientUpdate) SetPatientWeight(s string) *PatientUpdate {
	pu.mutation.SetPatientWeight(s)
	return pu
}

// SetPatientHeight sets the Patient_Height field.
func (pu *PatientUpdate) SetPatientHeight(s string) *PatientUpdate {
	pu.mutation.SetPatientHeight(s)
	return pu
}

// SetPatientPrefix sets the Patient_Prefix field.
func (pu *PatientUpdate) SetPatientPrefix(s string) *PatientUpdate {
	pu.mutation.SetPatientPrefix(s)
	return pu
}

// SetPatientGender sets the Patient_Gender field.
func (pu *PatientUpdate) SetPatientGender(s string) *PatientUpdate {
	pu.mutation.SetPatientGender(s)
	return pu
}

// SetPatientBlood sets the Patient_Blood field.
func (pu *PatientUpdate) SetPatientBlood(s string) *PatientUpdate {
	pu.mutation.SetPatientBlood(s)
	return pu
}

// AddPatientCoveredPersonIDs adds the Patient_CoveredPerson edge to CoveredPerson by ids.
func (pu *PatientUpdate) AddPatientCoveredPersonIDs(ids ...int) *PatientUpdate {
	pu.mutation.AddPatientCoveredPersonIDs(ids...)
	return pu
}

// AddPatientCoveredPerson adds the Patient_CoveredPerson edges to CoveredPerson.
func (pu *PatientUpdate) AddPatientCoveredPerson(c ...*CoveredPerson) *PatientUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pu.AddPatientCoveredPersonIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (pu *PatientUpdate) Mutation() *PatientMutation {
	return pu.mutation
}

// RemovePatientCoveredPersonIDs removes the Patient_CoveredPerson edge to CoveredPerson by ids.
func (pu *PatientUpdate) RemovePatientCoveredPersonIDs(ids ...int) *PatientUpdate {
	pu.mutation.RemovePatientCoveredPersonIDs(ids...)
	return pu
}

// RemovePatientCoveredPerson removes Patient_CoveredPerson edges to CoveredPerson.
func (pu *PatientUpdate) RemovePatientCoveredPerson(c ...*CoveredPerson) *PatientUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return pu.RemovePatientCoveredPersonIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (pu *PatientUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := pu.mutation.PatientName(); ok {
		if err := patient.PatientNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Name", err: fmt.Errorf("ent: validator failed for field \"Patient_Name\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientAge(); ok {
		if err := patient.PatientAgeValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Age", err: fmt.Errorf("ent: validator failed for field \"Patient_Age\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientWeight(); ok {
		if err := patient.PatientWeightValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Weight", err: fmt.Errorf("ent: validator failed for field \"Patient_Weight\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientHeight(); ok {
		if err := patient.PatientHeightValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Height", err: fmt.Errorf("ent: validator failed for field \"Patient_Height\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientPrefix(); ok {
		if err := patient.PatientPrefixValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Prefix", err: fmt.Errorf("ent: validator failed for field \"Patient_Prefix\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientGender(); ok {
		if err := patient.PatientGenderValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Gender", err: fmt.Errorf("ent: validator failed for field \"Patient_Gender\": %w", err)}
		}
	}
	if v, ok := pu.mutation.PatientBlood(); ok {
		if err := patient.PatientBloodValidator(v); err != nil {
			return 0, &ValidationError{Name: "Patient_Blood", err: fmt.Errorf("ent: validator failed for field \"Patient_Blood\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(pu.hooks) == 0 {
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PatientUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PatientUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PatientUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pu *PatientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   patient.Table,
			Columns: patient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		},
	}
	if ps := pu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.PatientName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientName,
		})
	}
	if value, ok := pu.mutation.PatientAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientAge,
		})
	}
	if value, ok := pu.mutation.PatientWeight(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientWeight,
		})
	}
	if value, ok := pu.mutation.PatientHeight(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientHeight,
		})
	}
	if value, ok := pu.mutation.PatientPrefix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientPrefix,
		})
	}
	if value, ok := pu.mutation.PatientGender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientGender,
		})
	}
	if value, ok := pu.mutation.PatientBlood(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientBlood,
		})
	}
	if nodes := pu.mutation.RemovedPatientCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.PatientCoveredPersonTable,
			Columns: []string{patient.PatientCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PatientCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.PatientCoveredPersonTable,
			Columns: []string{patient.PatientCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// PatientUpdateOne is the builder for updating a single Patient entity.
type PatientUpdateOne struct {
	config
	hooks    []Hook
	mutation *PatientMutation
}

// SetPatientName sets the Patient_Name field.
func (puo *PatientUpdateOne) SetPatientName(s string) *PatientUpdateOne {
	puo.mutation.SetPatientName(s)
	return puo
}

// SetPatientAge sets the Patient_Age field.
func (puo *PatientUpdateOne) SetPatientAge(s string) *PatientUpdateOne {
	puo.mutation.SetPatientAge(s)
	return puo
}

// SetPatientWeight sets the Patient_Weight field.
func (puo *PatientUpdateOne) SetPatientWeight(s string) *PatientUpdateOne {
	puo.mutation.SetPatientWeight(s)
	return puo
}

// SetPatientHeight sets the Patient_Height field.
func (puo *PatientUpdateOne) SetPatientHeight(s string) *PatientUpdateOne {
	puo.mutation.SetPatientHeight(s)
	return puo
}

// SetPatientPrefix sets the Patient_Prefix field.
func (puo *PatientUpdateOne) SetPatientPrefix(s string) *PatientUpdateOne {
	puo.mutation.SetPatientPrefix(s)
	return puo
}

// SetPatientGender sets the Patient_Gender field.
func (puo *PatientUpdateOne) SetPatientGender(s string) *PatientUpdateOne {
	puo.mutation.SetPatientGender(s)
	return puo
}

// SetPatientBlood sets the Patient_Blood field.
func (puo *PatientUpdateOne) SetPatientBlood(s string) *PatientUpdateOne {
	puo.mutation.SetPatientBlood(s)
	return puo
}

// AddPatientCoveredPersonIDs adds the Patient_CoveredPerson edge to CoveredPerson by ids.
func (puo *PatientUpdateOne) AddPatientCoveredPersonIDs(ids ...int) *PatientUpdateOne {
	puo.mutation.AddPatientCoveredPersonIDs(ids...)
	return puo
}

// AddPatientCoveredPerson adds the Patient_CoveredPerson edges to CoveredPerson.
func (puo *PatientUpdateOne) AddPatientCoveredPerson(c ...*CoveredPerson) *PatientUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return puo.AddPatientCoveredPersonIDs(ids...)
}

// Mutation returns the PatientMutation object of the builder.
func (puo *PatientUpdateOne) Mutation() *PatientMutation {
	return puo.mutation
}

// RemovePatientCoveredPersonIDs removes the Patient_CoveredPerson edge to CoveredPerson by ids.
func (puo *PatientUpdateOne) RemovePatientCoveredPersonIDs(ids ...int) *PatientUpdateOne {
	puo.mutation.RemovePatientCoveredPersonIDs(ids...)
	return puo
}

// RemovePatientCoveredPerson removes Patient_CoveredPerson edges to CoveredPerson.
func (puo *PatientUpdateOne) RemovePatientCoveredPerson(c ...*CoveredPerson) *PatientUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return puo.RemovePatientCoveredPersonIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (puo *PatientUpdateOne) Save(ctx context.Context) (*Patient, error) {
	if v, ok := puo.mutation.PatientName(); ok {
		if err := patient.PatientNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Name", err: fmt.Errorf("ent: validator failed for field \"Patient_Name\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientAge(); ok {
		if err := patient.PatientAgeValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Age", err: fmt.Errorf("ent: validator failed for field \"Patient_Age\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientWeight(); ok {
		if err := patient.PatientWeightValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Weight", err: fmt.Errorf("ent: validator failed for field \"Patient_Weight\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientHeight(); ok {
		if err := patient.PatientHeightValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Height", err: fmt.Errorf("ent: validator failed for field \"Patient_Height\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientPrefix(); ok {
		if err := patient.PatientPrefixValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Prefix", err: fmt.Errorf("ent: validator failed for field \"Patient_Prefix\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientGender(); ok {
		if err := patient.PatientGenderValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Gender", err: fmt.Errorf("ent: validator failed for field \"Patient_Gender\": %w", err)}
		}
	}
	if v, ok := puo.mutation.PatientBlood(); ok {
		if err := patient.PatientBloodValidator(v); err != nil {
			return nil, &ValidationError{Name: "Patient_Blood", err: fmt.Errorf("ent: validator failed for field \"Patient_Blood\": %w", err)}
		}
	}

	var (
		err  error
		node *Patient
	)
	if len(puo.hooks) == 0 {
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PatientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			mut = puo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, puo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PatientUpdateOne) SaveX(ctx context.Context) *Patient {
	pa, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return pa
}

// Exec executes the query on the entity.
func (puo *PatientUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PatientUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (puo *PatientUpdateOne) sqlSave(ctx context.Context) (pa *Patient, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   patient.Table,
			Columns: patient.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: patient.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Patient.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := puo.mutation.PatientName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientName,
		})
	}
	if value, ok := puo.mutation.PatientAge(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientAge,
		})
	}
	if value, ok := puo.mutation.PatientWeight(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientWeight,
		})
	}
	if value, ok := puo.mutation.PatientHeight(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientHeight,
		})
	}
	if value, ok := puo.mutation.PatientPrefix(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientPrefix,
		})
	}
	if value, ok := puo.mutation.PatientGender(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientGender,
		})
	}
	if value, ok := puo.mutation.PatientBlood(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: patient.FieldPatientBlood,
		})
	}
	if nodes := puo.mutation.RemovedPatientCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.PatientCoveredPersonTable,
			Columns: []string{patient.PatientCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PatientCoveredPersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   patient.PatientCoveredPersonTable,
			Columns: []string{patient.PatientCoveredPersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: coveredperson.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	pa = &Patient{config: puo.config}
	_spec.Assign = pa.assignValues
	_spec.ScanValues = pa.scanValues()
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patient.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return pa, nil
}
